# Image from https://hub.docker.com/_/gcc/ based on Debian
image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf
  script:
    - ./autogen.sh
    - ./configure
    - make
  artifacts:
    cache:
      paths:
        - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - make check
    - make distcheck

