# Image from https://hub.docker.com/_/gcc/ based on Debian
image: gcc

build:
  stage: build
  before_script:
    - apt-get update &&
      apt-get install -y libogg-dev libvorbis-dev libsdl-dev
        doxygen fig2dev texlive texlive-latex-extras
  script:
    - ./autogen.sh
    - ./configure
    - make
  cache:
    paths:
      - "*.o"
  tags:
    - docker
    - ovh

# run tests using the binary built before
test:
  stage: test
  script:
    - make check
    - make distcheck
  tags:
    - docker
    - ovh
