# Image from https://hub.docker.com/_/gcc/ based on Debian
image: gcc

build:
  stage: build
  before_script:
    - apt-get update &&
      apt-get install -y libogg-dev libvorbis-dev libsdl-dev
        doxygen fig2dev texlive texlive-latex-extra
  script:
    - ./autogen.sh
    - ./configure
    - make
    - make distcheck
  cache:
    paths:
      - "*.o"
  tags:
    - docker

cmake:
  stage: build
  script:
    - cd win32/VS2010; msbuild
  tags:
    - windows
